backend/config/routes.rb
Rails.application.routes.draw do
  get '/grids/lookup/:location', to: 'grids#lookup'
  get '/grids/colorupdate/:location/:index/:color', to: 'grids#colorupdate'
  resources :grids
  # add another route here for 
  #root 'grids#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/grid.rb
class Grid < ApplicationRecord
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

backend/app/controllers/grids_controller.rb
class GridsController < ApplicationController
  before_action :set_grid, only: [:show, :edit, :update, :destroy]

  #GET /grids/lookup/:location
  #GET /grids/lookup/:location.json
  def lookup
    respond_to do |format|
      @grid = Grid.find_by_location(params[:location])
      format.json {render json: @grid.colors, status: :ok, location: @grid }
    end
  end

  #GET /grids/colorupdate/:location/:index/:color
  #GET /grids/colorupdate/:location/:index/:color.json
  def colorupdate
      respond_to do |format|
          @location = params[:location]
          @index = params[:index].to_f
          @color = params[:color]
          @grid = Grid.find_by_location(@location)
          @newColorArray = @grid.colors
          @newColorArray[@index] = @color
          
          @grid.colors = @newColorArray
          @grid.save
          
          format.json {render json: @grid.colors, status: :ok, location: @grid}
    end
  end
  
  # GET /grids
  # GET /grids.json
  def index
    @grids = Grid.all
  end

  # GET /grids/1
  # GET /grids/1.json
  def show
    @grid = Grid.find(params[:id])
    @colors = @grid.colors
  end

  # GET /grids/new
  def new
    @grid = Grid.new
  end

  # GET /grids/1/edit
  def edit
    @grid = Grid.find(params[:id])
  end

  # POST /grids
  # POST /grids.json
  def create
    @grid = Grid.new(grid_params)
    respond_to do |format|
      if @grid.save
        format.html { redirect_to @grid, notice: 'Grid was successfully created.' }
        format.json { render :show, status: :created, location: @grid }
      else
        format.html { render :new }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
      # add something here to process info and send it back
      # use the render function
      #render text: "Test alert", status: 200
    end
  end

  # PATCH/PUT /grids/1
  # PATCH/PUT /grids/1.json
  def update
    respond_to do |format|
      if @grid.update(grid_params)
        format.html { redirect_to @grid, notice: 'Grid was successfully updated.' }
        format.json { render :show, status: :ok, location: @grid }
      else
        format.html { render :edit }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grids/1
  # DELETE /grids/1.json
  def destroy
    @grid.destroy
    respond_to do |format|
      format.html { redirect_to grids_url, notice: 'Grid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grid
     @grid = Grid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grid_params
      params.require(:grid).permit(:location, :colors)
    end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/grids_helper.rb
module GridsHelper
end

backend/app/views/grids/_form.html.erb
<%= form_with(model: grid, local: true) do |form| %>
  <% if grid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grid.errors.count, "error") %> prohibited this grid from being saved:</h2>

      <ul>
      <% grid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location, id: :grid_location %>
  </div>

  <div class="field">
    <%= form.label :colors %>
    <%= form.text_area :colors, id: :grid_colors %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/grids/edit.html.erb
<h1>Editing Grid</h1>

<%= render 'form', grid: @grid %>

<%= link_to 'Show', @grid %> |
<%= link_to 'Back', grids_path %>

backend/app/views/grids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grids</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Colors</th>
      <th colspan="3"></th>      
    </tr>
  </thead>

  <tbody>
    <% @grids.each do |grid| %>
      <tr>
        <td><%= grid.location %></td>
        <td><%= grid.colors %></td>
        <td><%= link_to 'Show', grid %></td>
        <td><%= link_to 'Edit', edit_grid_path(grid) %></td>
        <td><%= link_to 'Destroy', grid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grid', new_grid_path %>

backend/app/views/grids/new.html.erb
<h1>New Grid</h1>

<%= render 'form', grid: @grid %>

<%= link_to 'Back', grids_path %>

backend/app/views/grids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @grid.location %>
</p>

<p>
  <strong>Colors[]:</strong>
  <%= @grid.colors %>
</p>

<%= link_to 'Edit', edit_grid_path(@grid) %> |
<%= link_to 'Back', grids_path %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>